//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceImpuestos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    public partial class Factura : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceImpuestos.SerWebImpuestosSoap")]
    public interface SerWebImpuestosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sincronizarFechaHora", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceImpuestos.sincronizarFechaHoraResponse> sincronizarFechaHoraAsync(ServiceImpuestos.sincronizarFechaHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCufd", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceImpuestos.obtenerCufdResponse> obtenerCufdAsync(ServiceImpuestos.obtenerCufdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/emitirFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceImpuestos.emitirFacturaResponse> emitirFacturaAsync(ServiceImpuestos.emitirFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sincronizarFechaHoraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sincronizarFechaHora", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.sincronizarFechaHoraRequestBody Body;
        
        public sincronizarFechaHoraRequest()
        {
        }
        
        public sincronizarFechaHoraRequest(ServiceImpuestos.sincronizarFechaHoraRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sincronizarFechaHoraRequestBody
    {
        
        public sincronizarFechaHoraRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sincronizarFechaHoraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sincronizarFechaHoraResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.sincronizarFechaHoraResponseBody Body;
        
        public sincronizarFechaHoraResponse()
        {
        }
        
        public sincronizarFechaHoraResponse(ServiceImpuestos.sincronizarFechaHoraResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sincronizarFechaHoraResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sincronizarFechaHoraResult;
        
        public sincronizarFechaHoraResponseBody()
        {
        }
        
        public sincronizarFechaHoraResponseBody(string sincronizarFechaHoraResult)
        {
            this.sincronizarFechaHoraResult = sincronizarFechaHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCufdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCufd", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.obtenerCufdRequestBody Body;
        
        public obtenerCufdRequest()
        {
        }
        
        public obtenerCufdRequest(ServiceImpuestos.obtenerCufdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCufdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NIT;
        
        public obtenerCufdRequestBody()
        {
        }
        
        public obtenerCufdRequestBody(int idambiente, string modalidad, string NIT)
        {
            this.idambiente = idambiente;
            this.modalidad = modalidad;
            this.NIT = NIT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCufdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCufdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.obtenerCufdResponseBody Body;
        
        public obtenerCufdResponse()
        {
        }
        
        public obtenerCufdResponse(ServiceImpuestos.obtenerCufdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCufdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerCufdResult;
        
        public obtenerCufdResponseBody()
        {
        }
        
        public obtenerCufdResponseBody(string obtenerCufdResult)
        {
            this.obtenerCufdResult = obtenerCufdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emitirFacturaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emitirFactura", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.emitirFacturaRequestBody Body;
        
        public emitirFacturaRequest()
        {
        }
        
        public emitirFacturaRequest(ServiceImpuestos.emitirFacturaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class emitirFacturaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Nit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceImpuestos.Factura facturaa;
        
        public emitirFacturaRequestBody()
        {
        }
        
        public emitirFacturaRequestBody(int idambiente, int Nit, int modalidad, ServiceImpuestos.Factura facturaa)
        {
            this.idambiente = idambiente;
            this.Nit = Nit;
            this.modalidad = modalidad;
            this.facturaa = facturaa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class emitirFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="emitirFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceImpuestos.emitirFacturaResponseBody Body;
        
        public emitirFacturaResponse()
        {
        }
        
        public emitirFacturaResponse(ServiceImpuestos.emitirFacturaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class emitirFacturaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emitirFacturaResult;
        
        public emitirFacturaResponseBody()
        {
        }
        
        public emitirFacturaResponseBody(string emitirFacturaResult)
        {
            this.emitirFacturaResult = emitirFacturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SerWebImpuestosSoapChannel : ServiceImpuestos.SerWebImpuestosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SerWebImpuestosSoapClient : System.ServiceModel.ClientBase<ServiceImpuestos.SerWebImpuestosSoap>, ServiceImpuestos.SerWebImpuestosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SerWebImpuestosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SerWebImpuestosSoapClient.GetBindingForEndpoint(endpointConfiguration), SerWebImpuestosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerWebImpuestosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SerWebImpuestosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerWebImpuestosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SerWebImpuestosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerWebImpuestosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public SerWebImpuestosSoapClient()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceImpuestos.sincronizarFechaHoraResponse> ServiceImpuestos.SerWebImpuestosSoap.sincronizarFechaHoraAsync(ServiceImpuestos.sincronizarFechaHoraRequest request)
        {
            return base.Channel.sincronizarFechaHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceImpuestos.sincronizarFechaHoraResponse> sincronizarFechaHoraAsync()
        {
            ServiceImpuestos.sincronizarFechaHoraRequest inValue = new ServiceImpuestos.sincronizarFechaHoraRequest();
            inValue.Body = new ServiceImpuestos.sincronizarFechaHoraRequestBody();
            return ((ServiceImpuestos.SerWebImpuestosSoap)(this)).sincronizarFechaHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceImpuestos.obtenerCufdResponse> ServiceImpuestos.SerWebImpuestosSoap.obtenerCufdAsync(ServiceImpuestos.obtenerCufdRequest request)
        {
            return base.Channel.obtenerCufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceImpuestos.obtenerCufdResponse> obtenerCufdAsync(int idambiente, string modalidad, string NIT)
        {
            ServiceImpuestos.obtenerCufdRequest inValue = new ServiceImpuestos.obtenerCufdRequest();
            inValue.Body = new ServiceImpuestos.obtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modalidad = modalidad;
            inValue.Body.NIT = NIT;
            return ((ServiceImpuestos.SerWebImpuestosSoap)(this)).obtenerCufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceImpuestos.emitirFacturaResponse> ServiceImpuestos.SerWebImpuestosSoap.emitirFacturaAsync(ServiceImpuestos.emitirFacturaRequest request)
        {
            return base.Channel.emitirFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceImpuestos.emitirFacturaResponse> emitirFacturaAsync(int idambiente, int Nit, int modalidad, ServiceImpuestos.Factura facturaa)
        {
            ServiceImpuestos.emitirFacturaRequest inValue = new ServiceImpuestos.emitirFacturaRequest();
            inValue.Body = new ServiceImpuestos.emitirFacturaRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.Nit = Nit;
            inValue.Body.modalidad = modalidad;
            inValue.Body.facturaa = facturaa;
            return ((ServiceImpuestos.SerWebImpuestosSoap)(this)).emitirFacturaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SerWebImpuestosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SerWebImpuestosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SerWebImpuestosSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44342/SerWebImpuestos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SerWebImpuestosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44342/SerWebImpuestos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SerWebImpuestosSoap,
            
            SerWebImpuestosSoap12,
        }
    }
}
